Set Working dir

```{r}
setwd("~/Master/Functional_Annotation/GeneSCF")
```

loading libraries

```{r}
library(ggplot2)
library(ggrepel)
library(stringr)
library(gridtext)
library(ggtext)
```

BP_GO plot

```{r fig.height = 8, fig.width = 11}
data <- read.delim("output/gene_list.list_GO_BP_GO_bps_functional_classification.tsv", header=TRUE)
data <- data[order(data$P.value),]
size <- length(data[,1])
data[,"Rank_in_order"] <- c(seq(1:length(data[,1])))
data <- data[,cbind("Rank_in_order","Process.name","percentage.","P.value")]

colnames(data) <- c("Rank_in_order","process","genes","Pvalue")
data <- data[1:20,]
row.names(data) <- NULL

data$process = factor(data$process, levels=c(data$process))

#png(paste0("output/GO_BP_enrichment_plot.png"),width=1080,height=750)
ggplot(data, aes(x=Rank_in_order, y=-log10(Pvalue), size=genes, label=gsub( "~.*$", " ",process), fill= process))+
scale_size_area(max_size = 5)+ 
scale_x_continuous(name="Rank in order", limits=c(0,20))+
scale_y_continuous(name="-log10(Pvalue)")+
scale_fill_discrete(breaks = data$process)+
geom_point(colour="#2E2E2E", shape=21)+ 
#scale_size_continuous(range=c(1, 15))+
geom_text_repel(size=3, color="#2E2E2E", box.padding = 0.5)+
geom_hline(yintercept=1.3, linetype='dotted', col = 'red')+
labs(title = "20 Most enriched **Biological Process** Terms for *B. pseudomallei* biofilm-related genes",
fill="Biological Process (Top 20)")+
annotate("text", size = 3, x = 16, y = 1.3, label = "paste(italic(p), \"-value = 0.05\")", vjust = -1, parse = TRUE)+
theme(plot.title =element_markdown(hjust = -0.3, size=16),
text = element_text(size=12))
ggsave("output/GO_BP_enrichment_plot.png",dpi=300)
ggsave("output/GO_BP_enrichment_plot.tiff",dpi=300)
```

MF_GO plot

```{r fig.height = 8, fig.width = 11.2}
data <- read.delim("output/gene_list.list_GO_MF_GO_bps_functional_classification.tsv", header=TRUE)
data <- data[order(data$P.value),]
size <- length(data[,1])
data[,"Rank_in_order"] <- c(seq(1:length(data[,1])))
data <- data[,cbind("Rank_in_order","Process.name","percentage.","P.value")]

colnames(data) <- c("Rank_in_order","process","genes","Pvalue")
data <- data[1:20,]
row.names(data) <- NULL

data$process = factor(data$process, levels=c(data$process))

#png(paste0("output/GO_BP_enrichment_plot.png"),width=1080,height=750)
ggplot(data, aes(x=Rank_in_order, y=-log10(Pvalue), size=genes, label=gsub( "~.*$", " ",process), fill= process))+
scale_size_area(max_size = 5)+ 
scale_x_continuous(name="Rank in order", limits=c(0,20))+
scale_y_continuous(name="-log10(Pvalue)")+
scale_fill_discrete(breaks = data$process)+
geom_point(colour="#2E2E2E", shape=21)+ 
#scale_size_continuous(range=c(1, 15))+
geom_text_repel(size=3, color="#2E2E2E", box.padding = 0.4)+
geom_hline(yintercept=1.3, linetype='dotted', col = 'red')+
labs(title = "20 Most enriched **Molecular Function** Terms for *B. pseudomallei* biofilm-related genes",
fill="Molecular Function (Top 20)")+
annotate("text", size = 3, x = 16, y = 1.3, label = "paste(italic(p), \"-value = 0.05\")", vjust = -1, parse = TRUE)+
theme(plot.title =element_markdown(hjust = -0.3, size=16),
text = element_text(size=12))
ggsave("output/GO_MF_enrichment_plot.png",dpi=300)
ggsave("output/GO_MF_enrichment_plot.tiff",dpi=300)
```


CC_GO plot
```{r fig.height = 8, fig.width = 11}
data <- read.delim("output/gene_list.list_GO_CC_GO_bps_functional_classification.tsv", header=TRUE)
data <- data[order(data$P.value),]
size <- length(data[,1])
data[,"Rank_in_order"] <- c(seq(1:length(data[,1])))
data <- data[,cbind("Rank_in_order","Process.name","percentage.","P.value")]

colnames(data) <- c("Rank_in_order","process","genes","Pvalue")
data <- data[1:20,]
row.names(data) <- NULL

data$process = factor(data$process, levels=c(data$process))

#png(paste0("output/GO_BP_enrichment_plot.png"),width=1080,height=750)
ggplot(data, aes(x=Rank_in_order, y=-log10(Pvalue), size=genes, label=gsub( "~.*$", " ",process), fill= process))+
scale_size_area(max_size = 5)+ 
scale_x_continuous(name="Rank in order", limits=c(0,20))+
scale_y_continuous(name="-log10(Pvalue)")+
scale_fill_discrete(breaks = data$process)+
geom_point(colour="#2E2E2E", shape=21)+ 
#scale_size_continuous(range=c(1, 15))+
geom_text_repel(size=3, color="#2E2E2E", box.padding = 0.4)+
geom_hline(yintercept=1.3, linetype='dotted', col = 'red')+
labs(title = "20 Most enriched **Cellular Component** Terms for *B. pseudomallei* biofilm-related genes",
fill="Cellular Component (Top 20)")+
annotate("text", size = 3, x = 16, y = 1.3, label = "paste(italic(p), \"-value = 0.05\")", vjust = -1, parse = TRUE)+
theme(plot.title =element_markdown(hjust = -0.3, size=16),
text = element_text(size=12))
ggsave("output/GO_CC_enrichment_plot.png",dpi=300)
ggsave("output/GO_CC_enrichment_plot.tiff",dpi=300)
```


KEGG plot
```{r fig.height = 8, fig.width = 11}
data <- read.delim("output/gene_list.list_KEGG_bps_functional_classification.tsv", header=TRUE)
data <- data[order(data$P.value),]
size <- length(data[,1])
data[,"Rank_in_order"] <- c(seq(1:length(data[,1])))
data <- data[,cbind("Rank_in_order","Process.name","percentage.","P.value")]

colnames(data) <- c("Rank_in_order","process","genes","Pvalue")
data <- data[1:20,]
row.names(data) <- NULL

data$process = factor(data$process, levels=c(data$process))

#png(paste0("output/GO_BP_enrichment_plot.png"),width=1080,height=750)
ggplot(data, aes(x=Rank_in_order, y=-log10(Pvalue), size=genes, label=gsub( "~.*$", " ",process), fill= process))+
scale_size_area(max_size = 5)+ 
scale_x_continuous(name="Rank in order", limits=c(0,20))+
scale_y_continuous(name="-log10(Pvalue)")+
scale_fill_discrete(breaks = data$process)+
geom_point(colour="#2E2E2E", shape=21)+ 
#scale_size_continuous(range=c(1, 15))+
geom_text_repel(size=3, color="#2E2E2E", box.padding = 0.5)+
geom_hline(yintercept=1.3, linetype='dotted', col = 'red')+
labs(title = "20 Most enriched **KEGG** Terms for *B. pseudomallei* biofilm-related genes",
fill="KEGG Terms (Top 20)")+
annotate("text", size = 3, x = 1, y = 1.3, label = "paste(italic(p), \"-value = 0.05\")", vjust = -1, parse = TRUE)+
theme(plot.title =element_markdown(hjust = -1.5, size=16),
text = element_text(size=12))
ggsave("output/KEGG_enrichment_plot.png",dpi=300)
ggsave("output/KEGG_enrichment_plot.tiff",dpi=300)
```